---
.job:
  stage: test
  script:
    - echo $CI_JOB_NAME

variables:
  # renovate: datasource=docker depName=keycloak/keycloak
  KEYCLOAK_VERSION: 18.0.0
  # renovate: datasource=github-releases depName=passbolt/passbolt_api
  PASSBOLT_VERSION: 4.0.0

job1:
  extends: .job
  image: ${CI_DEPENDENCY_PROXY_GROUP_IMAGE_PREFIX}/aquasec/trivy:0.37.0@sha256:3cea372a13cbb9ae466ebac8213acc5217e5a396744dc937d8d1092d6b18f12c

job2:
  extends: .job
  image: node:18.17.1-bullseye-slim@sha256:07146b353bfe5ab1984cd706a942f5dac65de7d24866ba68a8f17cccc5ba3bd1

job3:
  extends: .job
  image: ${CI_TEMPLATE_REGISTRY_HOST}/gitlab-org/terraform-images/releases/1.4:v0.52.0

job4:
  extends: .job
  image: ghcr.io/terraform-linters/tflint-bundle:v0.45.0.1@sha256:498abf1572842654cb92b4c55f8aec9763790438108ac4f4e7b6b60be11ea7e0

job5:
  extends: .job
  image: quay.io/keycloak/keycloak:22.0.1@sha256:89b37fa67c6d48b08637f5b6fb891785bd679e0bc15ee6c68eaab479c1cef7b1
